# --- Change Vars ----
run-group: !!str pet-food
amazon_data_scraper: &amazon_data_scraper
  run-name: !!str pet-wet-food
  run-type: !!str extract

# --- Default Template ---
defaults: &default
  min_page_index: !!str 1
  extract:
    file-name: !!str extract_{category_name}_data.json
    run-script: !!str extract/scraper_extractor.py
  transform:
    file-name: !!str transform_{category_name}_data.json
    run-script: !!str transform/scraper_transformer.py
  load:
    file-name: !!str amazonae_{category_name}_{timestamp}.csv
    run-script: !!str load/scraper_load.py
  upload:
    file-name: !!str ""
    run-script: !!str scraper_data_loader.py

# --- Electronics Category ---
electronics:
  name: !!str Electronics
  <<: *amazon_data_scraper
  camera-photo:
    name: !!str Camera & Photo
    <<: *default
    url_template: !!str https://www.amazon.co.za/s?i=electronics&rh=n%3A28034765031&s=popularity-rank&fs=true&page={page_index}&xpid=fCSbRWnd8cea8&qid=1750423778&ref=sr_pg_{page_index}

  headphones-earbuds-accessory:
    name: !!str Headphones, Earbuds & Accessories
    <<: *default
    url_template: !!str https://www.amazon.co.za/s?i=electronics&rh=n%3A28034761031&s=popularity-rank&fs=true&page={page_index}&qid=1750425462&xpid=sumlClfMQTKfk&ref=sr_pg_{page_index}
 

 
# --- Pet Food Category ---
pet-food:
  name: !!str pet food
  <<: *amazon_data_scraper
  pet-wet-food:
    name: !!str pet wet food
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=pet+wet+food&page={page_index}&xpid=eG00IPfKkR-7r&crid=ZR8TFY604D60&qid=1747758936&sprefix=pet+wet+food%2Caps%2C249&ref=sr_pg_{page_index}

  pet-dry-food:
    name: !!str pet dry food
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=pet+dry+food&page={page_index}&crid=182X5RT13JDLF&qid=1747116730&sprefix=pet+dry+food%2Caps%2C341&xpid=t5xbaJgfii7Z2&ref=sr_pg_{page_index}

# --- Food & beverage Category ---
food-beverage:
  name: food & beverage
  ground-coffee:
    name: !!str ground coffee
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=ground+coffee&page={page_index}&xpid=0JFIgTfeNSVY0&crid=1D9VA37FP5MTE&qid=1747746568&sprefix=ground+coffe%2Caps%2C281&ref=sr_pg_{page_index}

# --- Pet Accessories ---
pet-accessories:
  name: !!str pet accessories
  <<: *amazon_data_scraper
  collar-leash:
    name: !!str collars & leashes
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=pet+accessories+collars+%26+leashes&i=pets&page={page_index}&crid=3N8Q9DO1CD16Y&qid=1749002781&sprefix=pet+accessories+collars+%26+leashes%2Cpets%2C382&xpid=TPZy3yrhc63yy&ref=sr_pg_{page_index}

  pet-bowl-container:
    name: !!str pwt bowls & container
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=pet+accessories+pet+bowls+%26container&i=pets&page={page_index}&xpid=rONcTayodwiPA&crid=1A8QIF2Y7J0O1&qid=1749003202&sprefix=pet+accessories+pet+bowls+%26containner%2Cpets%2C1132&ref=sr_pg_{page_index}

  carriers-travel-gear:
    name: !!str carriers & travel gear
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=pet+accessories+Carriers+%26+Travel+Gear&i=pets&page={page_index}&xpid=NhUOp6eRoxXoK&crid=229JY1J0D0FS0&qid=1749003792&sprefix=pet+accessories+carriers+%26+travel+gear%2Cpets%2C805&ref=sr_pg_{page_index}

# --- Pet Health & Grooming ---
pet-health-grooming:
  name: !!str pet health & grooming
  <<: *amazon_data_scraper
  supplement-vitamin:
    name: !!str supplements & vitamins
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=Pet+Health+%26+Grooming+Supplements+%26+Vitamins&i=pets&page={page_index}&xpid=-OCzfNwDgGkxM&crid=1B64R88LQLVZL&qid=1749004121&sprefix=pet+health+%26+grooming+supplements+%26+vitamins%2Cpets%2C588&ref=sr_pg_{page_index}

  treatment:
    name: !!str treatments
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=Pet+Health+%26+Grooming+treatments&i=pets&page={page_index}&xpid=wjPHa03iqd-eu&crid=3EAIRWQYL6OEC&qid=1749004361&sprefix=pet+health+%26+grooming+treatments%2Cpets%2C675&ref=sr_pg_{page_index}

  pet-toiletries:
    name: !!str pet toiletries
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=Pet+Health+%26+Grooming+pet+toiletries&i=pets&page={page_index}&xpid=qaxKjFDutVTGg&crid=295KTFWB0CLKG&qid=1749004498&sprefix=pet+health+%26+grooming+pet+toiletries%2Cpets%2C599&ref=sr_pg_{page_index}

# --- Pet Toys & Entertainment ---
pet-toy-entertainment:
  name: !!str pet toys & entertainment
  <<: *amazon_data_scraper
  chew-toy-ball:
    name: !!str chews toys & balls
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=Pet+Toys+%26+Entertainment+Chew+Toys+%26+Balls&i=pets&page={page_index}&xpid=D_rwU1O4xPPJ-&crid=1BT0RN3FBCPGT&qid=1749004977&sprefix=pet+toys+%26+entertainment+chew+toys+%26+balls%2Cpets%2C720&ref=sr_pg_{page_index}

  interactive-toys:
    name: !!str interactive toys
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=Pet+Toys+%26+Entertainment+interactive+toys&i=pets&page={page_index}&xpid=JFvyAGf4oQvT1&crid=6IXH0IW2I59O&qid=1749029633&sprefix=pet+toys+%26+entertainment+chew+toys+%26+balls%2Cpets%2C1147&ref=sr_pg_{page_index}

  scratching-posts:
    name: !!str scratching posts
    <<: *default
    url_template: !!str https://www.amazon.ae/s?k=Pet+Toys+%26+Entertainment+scratching+posts&i=pets&page={page_index}&xpid=U6VhRXBUPNfQ2&crid=2F1D8JDYXLTJF&qid=1749029797&sprefix=pet+toys+%26+entertainment+scratching+posts%2Cpets%2C1357&ref=sr_pg_{page_index}


# task cli-runner:extract MAX=10 RUN_GROUP=pet-toy-entertainment RUN_NAME=scratching-posts
# task cli-runner:extract \
#   MAX=10 \
#   RUN_GROUP=pet-toy-entertainment \
#   RUN_NAME=interactive-toys

# task cli-runner:extract \
#      MAX=10 \
#      RUN_GROUP=pet-toy-entertainment \
#       RUN_NAME=chew-toy-ball