---
version: '3'

vars:
  MARKET_PLACE: '{{.MARKET_PLACE | default ""}}'
  CATEGORY: '{{.CATEGORY | default ""}}'
  SUBCATEGORY: '{{.SUBCATEGORY | default ""}}'

includes:
  # docker: ./taskfiles/DockerTaskfile.yml
  cli-runner: ./taskfiles/RunCLI.yml

tasks:
  default:
    cmds:
      - task --list
    silent: true
