apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-{{ .Values.volume.volInspect }}"
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      resources:
        requests:
          memory: "32Mi"
          cpu: "10m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      volumeMounts:
        - name: {{ .Values.volume.name }}
          mountPath: {{ .Values.volume.mountPath }}
  volumes:
    - name: {{ .Values.volume.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.volume.claimName }}
  restartPolicy: Never
